apiVersion: hmc.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: motel-regional
spec:
  servicesPriority: 1000
  clusterSelector:
    matchLabels:
      motel: regional
  services:
    - template: motel-regional-0-1-5
      name: motel-regional
      namespace: motel