{{- if (index .Values "victoriametrics" "vmauth" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-select
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - drop_src_path_prefix_parts: 1
    paths:
    - /vls/.*
    static:
      url: http://motel-victoria-logs-single-server.mon.svc:9428
  - drop_src_path_prefix_parts: 1
    paths:
    - /vmk/select/.*
    static:
      url: http://vmselect-cluster.mon.svc:8481
  - drop_src_path_prefix_parts: 1
    paths:
    - /vm/insert/.*
    static:
      url: http://vminsert-cluster.mon.svc:8480
  username: {{ .Values.victoriametrics.vmauth.username }}
  password: {{ .Values.victoriametrics.vmauth.password }}
  # generatePassword: true
{{- end }}