global:
  clusterLabel: clusterName
  storageClass: gp2
  clusterName: regional
cert-manager:
  enabled: true
  email: mail@weystrom.net
victoriametrics:
  enabled: true
  vmauth:
    enabled: true
  vmcluster:
    enabled: true
  vmalert:
    enabled: true
  vmagent:
    enabled: false
grafana:
  enabled: true
  datasource:
    url: http://vmselect-cluster:8481/select/0/prometheus
  alerts:
    enabled: true
victoria-metrics-operator:
  enabled: true
  crds:
    plain: true
victoria-logs-single:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      storageClassName: gp2
  fluent-bit:
    enabled: false